ds_blog/urls.py
from django.conf.urls import url
from ds_blog import views

app_name = "ds_blog"
urlpatterns=[
            # url(r'^index/',views.index,name='index'),
            url(r'^seattle_data/',views.myseattle,name='myseattle'),
            url(r'^list/',views.list,name='list'),
            url(r'^logistic_regression/',views.logistic_regression,
                                    name='logistic_regression'),
            url(r'^linear_regression/',views.linear_regression,
                                    name='linear_regression'),
            url(r'^pseudospectral/',views.pseudospectral,
                                    name='pseudospectral'),
            url(r'^pseudospectral-functions/',views.pseudospectral_blog1,
                                    name='pseudospectral_blog1'),
            url(r'^evaluation-metrics-regression/',views.evaluation_metrics1,
                                    name='evaluation_metrics1'),
            url(r'^introduction/',views.introduction,
                                    name='introduction'),
]

project_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from ds_blog import views



urlpatterns = [
    url(r'^ds-blog/',include('ds_blog.urls', namespace="ds_blog")),
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ds_blog/models.py
from django.db import models

# Create your models here.

ds_blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

image_list = [('penn_waterfall1.jpg','Waterfall'),
    ('penn_fallcolors1_cropped.jpg','Fall Colors'),
    ('maine1.jpg','Maine'),
    ('nz_flower.jpg','NZ Flower'),
    ('nz_beach1.jpg','NZ Beach 1'),
    ('nz_beach2.jpg','NZ Beach 2'),
    ('nz_beach3.jpg','NZ Beach 3'),
    ('nz4.jpg','NZ 4'),
    ('nz5.jpg','NZ 5'),
    ('nz6.jpg','NZ 6'),
    ]

def penn(request):
    context_dic = {'imgs': image_list}
    return render(request,'ds_blog/penn.html',context_dic)

def index(request):
    return render(request,'ds_blog/index.html')


def myseattle(request):
    return render(request,'ds_blog/notebooks/seattle_bicycle/seattle_bicycle_data.html')

def logistic_regression(request):
    context_dic = {'imgs': image_list}
    return render(request,'ds_blog/logisticRegression.html',context_dic)


def linear_regression(request):
    context_dic = {'imgs': image_list}
    return render(request,'ds_blog/linearRegression.html',context_dic)

def pseudospectral(request):
    context_dic = {'imgs': image_list}
    return render(request,'ds_blog/notebooks/pseudospectral_continuation/pseudospectral_example.html',context_dic)

def pseudospectral_blog1(request):
    context_dic = {'imgs': image_list}
    return render(request,'ds_blog/pseudospectral_blog1.html')

def evaluation_metrics1(request):
    context_dic = {'imgs': image_list}
    return render(request,'ds_blog/EvaluationMetrics1.html',context_dic)

def introduction(request):
    # context_dic = {'imgs': image_list}
    return render(request,'ds_blog/introduction.html')#,context_dic)

def list(request):
    return render(request,'ds_blog/bloglist.html')

templates/appHome/bloglist.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
<!-- <style media="screen" type="text/css">

.imagediv{
max-width: 50%;
float:left;
margin: 1em;
margin-bottom: 0em;
margin-left:.5em;
padding-right:8px;
padding-left:0px;
padding-bottom:0px;
}
.trialform{
  display:none;
}
</style> -->



<!-- size="6" color="#05d251" -->

<div style="width:650px;">
  <div class="" style="padding-top:50px;">

  </div>

  <article class="post">
    <a href="{% url 'appHome:pseudospectral_blog1' %}">
      <h3 class="post">Pseudospectral Approximation of Functions</h3>
      <div class="meta_author">
      April 6, 2018  &nbsp; &bull; &nbsp; Joshua Lytle
      </div>
      My graduate research at BYU relied on good boundary value problem (BVP) solvers.
      So I had the chance to review a lot of what was already implemented in Python, and build several of my own implementations.
      One approach that I've really enjoyed learning about is the pseudospectral method.
      This blog post will focus on approximating functions with Chebychev polynomials.
      I plan to eventually discuss a pseudospectral BVP solver.
    </a>
  </article>

  <!-- <hr>

  <article class="post">
    <a href="{% url 'appHome:logistic_regression' %}">
      <h3 class="post">Logistic Regression</h3>
      <div class="meta_author">
      March 30, 2018  &nbsp; &bull; &nbsp; Joshua Lytle
      </div>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </a>
  </article>

  <hr>
  <article class="post">
    <a href="{% url 'appHome:linear_regression' %}">
      <h3 class="post">Linear Regression</h3>
      <div class="meta_author">
      March 30, 2018  &nbsp; &bull; &nbsp; Joshua Lytle
      </div>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </a>
  </article> -->

  <hr>
  <article class="post">
    <a href="{% url 'appHome:evaluation_metrics1' %}">
      <h3 class="post">Evaluation Metrics for Regression Models</h3>
      <div class="meta_author">
      April 6, 2018  &nbsp; &bull; &nbsp; Joshua Lytle
      </div>
      So I recently wanted to clarify my thinking about two commonly used error metrics for evaluating regression models - mean absolute error (MAE) and root mean squared error (RMSE).
      These metrics accomplish similar tasks, but each have their own advantages.
      Let  $\mathcal{E} = (e_1,\ldots,e_n)^T$ be the model errors over the test data $(x_i,y_i)$.

      MAE is a straightforward mean of the absolute value of the errors, $\frac{1}{n}\sum_{i=1}^n |e_i|$.

      RMSE is the square root of the mean of the squared errors, $\sqrt{ \frac{1}{n}\sum_{i=1}^n e_i^2 \,}$.
    </a>
  </article>

  <!-- <hr> -->


</div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

  <head>
    <meta charset="utf-8">
                <!-- Data Science <span class='blue-shift'>Blue-Shifted</span>  -->
    <title>
      Joshua Lytle's Blog
    </title>
    <link rel="icon" href="{% static 'DS.png' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" property="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css">

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
    <!-- <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
      tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
      // availableFonts: ["STIX"],
      scale: 80
                   });
    </script> -->


    <script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js"],
    // jax: ["input/TeX", "output/HTML-CSS"],
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
      processEscapes: true
    },
    "HTML-CSS": {scale: 10 },
    "SVG":{scale:60}
  });
</script>

<!-- <script>
    var MathJax = {"HTML-CSS": {scale: 130}};
</script> -->
<!-- <script type="text/javascript" src="path-to-MathJax/MathJax.js">
</script> -->


    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'>
    </script>



<!-- <script type="text/javascript" async
src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script> -->

  </head>


  <body>
            <!-- Data Science <span class='blue-shift'>Blue-Shifted</span>  -->
<!-- id="fullWrap" -->
    <div id="fullWrap">
      <div id="fullHeader">
        <div class="centerWrap">
          <h1>
            <i class="fa fa-cubes btn-select" onclick="window.location.assign('{% url 'index' %}');" style="margin-right:.5em;"></i>
            Joshua Lytle's Blog
          </h1>
          <div id="menuSection">

            <div class="menuBtn btn-select" onclick="window.location.assign('{% url 'ds_blog:list' %}');">Blog</div>



            <div class="dropTab">
              <div class="menuBtn">
                Personal<i class="fa fa-angle-down" style="margin-left:.15em;"></i>
              </div>
              <div class="dropBox">
                <div class="dropBtn" onclick="window.location.assign('{% url 'ds_blog:introduction' %}');">
                  About
                </div>
                <div class="dropBtn" onclick="window.location.assign('{% url 'index' %}');">
                  Research
                </div>
                <div class="dropBtn" onclick="newwin('{% static "ds_blog/Resume_Joshua-Lytle.pdf" %}');">
                  <!-- <a href="{% static "ds_blog/Resume_Joshua-Lytle.pdf" %}">Resume</a>  -->
                  Resume
                </div>
              </div>
              <!-- End dropBox -->
            </div>
            <!-- End dropTab -->

          </div>
        </div>
      </div>

      <div id="bodySection">
        <div class="centerWrap">

          <!-- <div class="imagediv">
            <img id="imgid" class="trialimg" src="{% static 'penn_waterfall1.jpg' %}">
            <div>View from the parking lot. Ten minutes from the office by foot.</div>
            <form class="trialform" id="pictid" action="penn.html" method="get">
              <select id="selectid" class="trialsel" name="penn-images" onChange="resrc(reval().substring(1));">
                {% for val in imgs %}
                <option class="trialobj" value="{% static val.0 %}"> {{ val.1 }} </option>
                {% endfor %}
              </select>
            </form>
            <div style="clear:both;"></div>
          </div> -->




          <div class="" style="width:880px;padding:10px;">

            {% block body_block %}

            {% endblock %}


            <!-- <a href="main.pdf" download="Documentation.pdf">solitons.pdf</a> -->



          </div>
        </div>
      </div>
    </div>
  </body>
  <script type="text/javascript" src={% static "main.js" %}></script>
</html>

templates/ds_blog/EvaluationMetrics1.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}


<div class="blog_post">

  <h2 style="text-align:left;">
    Evaluation Metrics for Regression
  </h2>
  <div class="meta_author" style="margin-left:.8em;">
  April 6, 2018 &nbsp; &bull; &nbsp; Joshua Lytle
  </div>

  <p>
  So I recently wanted to clarify my thinking about two commonly used error metrics for evaluating regression models - mean absolute error (MAE) and root mean squared error (RMSE).
  These metrics accomplish similar tasks, but each have their own advantages.
  Let  $\mathcal{E} = (e_1,\ldots,e_n)^T$ be the model errors over the test data $(x_i,y_i)$.

  MAE is a straightforward mean of the absolute value of the errors, $\frac{1}{n}\sum_{i=1}^n |e_i|$.

  RMSE is the square root of the mean of the squared errors, $\sqrt{ \frac{1}{n}\sum_{i=1}^n e_i^2 \,}$.
  </p>

  <p>
    Both of these metrics have several nice properties.
    In both cases, the positive and negative errors cannot cancel out.
    Also, both metrics have the nice property that their units are the same as those of the output variable $y$.  So how are they different?
  </p>

  <p>
    Well, the mean absolute error makes more intuitive sense. I do have to grasp a little more to understand RMSE.  RMSE does have an interesting advantange of its own: when used as a loss function in a Machine Learning model, it is easy to take its derivatives.
  </p>

  <p>
    To find more about how these two metrics compare, let's look at several inequalities for norms:
    $$\|\mathcal{E}\|_2 \leq \|\mathcal{E}\|_1 \leq \sqrt{n}\|\mathcal{E}\|_2.$$
    Since $MAE = \frac{1}{n}\|\mathcal{E}\|_1$ and $RMSE = \frac{1}{\sqrt{n}}\|\mathcal{E}\|_2$, we can find two inequalities for these metrics:
    \begin{eqnarray}
    RMSE &\geq & MAE, \\
    RMSE &\leq & \sqrt{n}\, MAE.
    \end{eqnarray}
  </p>

  <p>
    So to summarize, root mean squared error is always bigger than mean absolute error. The second inequality above points toward an interesting tendency of root mean squared error: RMSE tends to grow as the size of the dataset grows. Something to be aware of, and not necessarily freak out about. Outliers in the data tend to affect RMSE more. Chai and Draxley (2014) have a great paper for further reading on this topic: <i>RMSE or MAE? - Arguments against avoiding RMSE in the literature</i>.
  </p>


  <!-- <p>
    While it is fairly obvious how MAE should be interpreted, RMSE is not as easily interpreted or related to MAE.
    So here we cover a couple useful inequalities involving these metrics. The first uses
    Jensen's inequality, which states that for a convex function $\phi$, there is the inequality $\phi(\mathbb{E}(x)) \leq \mathbb{E}(\phi(x)).$ Of course the inequality goes the other way for a concave function. Applying Jensen's inequality with $\phi(x) = \sqrt{x}$, we immediately get
    $$
      RMSE \geq MAE.
    $$
    (Remember that $|x| = \sqrt{x^2}.$)
  </p> -->



</div>


{% endblock %}

templates/ds_blog/bloglist.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
<!-- <style media="screen" type="text/css">

.imagediv{
max-width: 50%;
float:left;
margin: 1em;
margin-bottom: 0em;
margin-left:.5em;
padding-right:8px;
padding-left:0px;
padding-bottom:0px;
}
.trialform{
  display:none;
}
</style> -->


<div style="width:700px;padding-top:50px;min-height:600px;">


  <article class="post">
    <a href="{% url 'ds_blog:pseudospectral_blog1' %}">
      <h3 class="post">Pseudospectral Approximation of Functions</h3>
      <div class="meta_author">
      April 6, 2018  &nbsp; &bull; &nbsp; Joshua Lytle
      </div>
      My graduate research at BYU relied on good boundary value problem (BVP) solvers.
      So I had the chance to review a lot of what was already implemented in Python, and build several of my own implementations.
      One approach that I've really enjoyed learning about is the pseudospectral method.
      This blog post will focus on approximating functions with Chebychev polynomials.
      I plan to eventually discuss a pseudospectral BVP solver.
    </a>
  </article>

  <!-- <hr>

  <article class="post">
    <a href="{% url 'ds_blog:logistic_regression' %}">
      <h3 class="post">Logistic Regression</h3>
      <div class="meta_author">
      March 30, 2018  &nbsp; &bull; &nbsp; Joshua Lytle
      </div>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </a>
  </article>

  <hr>
  <article class="post">
    <a href="{% url 'ds_blog:linear_regression' %}">
      <h3 class="post">Linear Regression</h3>
      <div class="meta_author">
      March 30, 2018  &nbsp; &bull; &nbsp; Joshua Lytle
      </div>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </a>
  </article> -->

  <hr>
  <article class="post">
    <a href="{% url 'ds_blog:evaluation_metrics1' %}">
      <h3 class="post">Evaluation Metrics for Regression Models</h3>
      <div class="meta_author">
      April 6, 2018  &nbsp; &bull; &nbsp; Joshua Lytle
      </div>
      So I recently wanted to clarify my thinking about two commonly used error metrics for evaluating regression models - mean absolute error (MAE) and root mean squared error (RMSE).
      These metrics accomplish similar tasks, but each have their own advantages.
      Let  $\mathcal{E} = (e_1,\ldots,e_n)^T$ be the model errors over the test data $(x_i,y_i)$.

      MAE is a straightforward mean of the absolute value of the errors, $\frac{1}{n}\sum_{i=1}^n |e_i|$.

      RMSE is the square root of the mean of the squared errors, $\sqrt{ \frac{1}{n}\sum_{i=1}^n e_i^2 \,}$.
    </a>
  </article>

  <!-- <hr> -->


</div>



{% endblock %}

templates/ds_blog/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

  <head>
    <meta charset="utf-8">
          <!-- Data Science Blue-Shifted -->
    <title>
      Joshua Lytle's Blog
    </title>
    <link rel="icon" href="{% static 'DS.png' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" property="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css">

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
    <!-- <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
      tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
      // availableFonts: ["STIX"],
      scale: 80
                   });
    </script> -->


    <script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js"],
    // jax: ["input/TeX", "output/HTML-CSS"],
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
      processEscapes: true
    },
    "HTML-CSS": {scale: 10 },
    "SVG":{scale:60}
  });
</script>

<!-- <script>
    var MathJax = {"HTML-CSS": {scale: 130}};
</script> -->
<!-- <script type="text/javascript" src="path-to-MathJax/MathJax.js">
</script> -->


    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'>
    </script>



<!-- <script type="text/javascript" async
src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script> -->

  </head>


  <body>
            <!-- Data Science <span class='blue-shift'>Blue-Shifted</span>  -->
    <div id="fullWrap">
      <div id="fullHeader">
        <div class="centerWrap">
          <h1>
            <i class="fa fa-cubes btn-select" onclick="window.location.assign('{% url 'index' %}');" style="margin-right:.5em;"></i>
            Joshua Lytle's Blog
          </h1>
          <div id="menuSection">

            <div class="menuBtn btn-select" onclick="window.location.assign('{% url 'ds_blog:list' %}');">Blog</div>

            <!-- <div class="dropTab">
              <div class="menuBtn">Notebooks<i class="fa fa-angle-down" style="margin-left:.15em;"></i></div>
              <div class="dropBox">
                <div id="abutton" class="dropBtn"> <a href="{% url 'ds_blog:myseattle' %}">Seattle Bike Data</a> </div>
                <div id="seattle" class="dropBtn" onclick="newwin('{% url 'ds_blog:myseattle' %}');">Seattle Bike Data</div>
                <div id="pseudo" class="dropBtn" onclick="newwin('{% url 'ds_blog:pseudospectral' %}');">Pseudospectral Method</div>
              </div>
            </div> -->

            <div class="dropTab">
              <div class="menuBtn">Personal<i class="fa fa-angle-down" style="margin-left:.15em;"></i></div>
              <div class="dropBox">
                <div class="dropBtn" onclick="window.location.assign('{% url 'ds_blog:introduction' %}');">
                  About
                </div>
                <div class="dropBtn" onclick="window.location.assign('{% url 'index' %}');">
                  Research
                </div>
                <div class="dropBtn">
                  <a href="{% static "ds_blog/Resume_Joshua-Lytle.pdf" %}">Resume</a>
                </div>
              </div>
            </div>


          </div>
        </div>
      </div>

      <div id="bodySection">
        <div class="centerWrap">

          <!-- <div class="imagediv">
            <img id="imgid" class="trialimg" src="{% static 'penn_waterfall1.jpg' %}">
            <div>View from the parking lot. Ten minutes from the office by foot.</div>
            <form class="trialform" id="pictid" action="penn.html" method="get">
              <select id="selectid" class="trialsel" name="penn-images" onChange="resrc(reval().substring(1));">
                {% for val in imgs %}
                <option class="trialobj" value="{% static val.0 %}"> {{ val.1 }} </option>
                {% endfor %}
              </select>
            </form>
            <div style="clear:both;"></div>
          </div> -->




          <div class="" style="margin-top:150px;padding-left:10px;">
<!-- <h2 style="text-align:left;margin-bottom:0px;margin-top:100px;"> Joshua Lytle</h2> -->
            <div class="index_Menu_div" style="margin-top:60px;padding-top:20px;">
              <p id="index_Menu_main" class="index_Menu" style="background:#eee;">
                <a href="#">Research</a>
              </p>
              <p class="index_Menu">
                <a href="{% url 'ds_blog:list' %}">Blog</a>
              </p>
              <div class="" >
                <p class="index_Menu" onclick="newwin('https://github.com/joshualy');">
                  <!-- <a href="https://github.com/joshualy">GitHub</a> -->
                  GitHub
                </p>
              </div>

              <p class="index_Menu" onclick="newwin('{% static "ds_blog/Resume_Joshua-Lytle.pdf" %}');">
                <!-- <a href="{% static "ds_blog/Resume_Joshua-Lytle.pdf" %}">Resume</a> -->
                Resume
              </p>
            </div>

          </div>

          <div style="width:700px;margin-left:190px;margin-top:180px;padding-right:10px;">
            <h3>Background</h3>
            <p>
              I graduated from BYU  with a PhD in mathematics (June 2017).
              As a graduate student I was able to pursue my interests in PDEs and functional and numerical analysis, through studying numerically the stability properties of traveling wave solutions to nonlinear PDEs.
              Along the way I developed interests in Python programming and data science.
            </p>

            <p>
              While at BYU I studied multidimensional viscous detonations in the reactive Navier-Stokes equations.
              Detonations are usually studied in the inviscid setting.
              My colleague Blake Barker and several others had just looked at viscous detonations for the rNS equations; we then looked at the stability properties of multidimensional detonations.
              Because of the multi-parameter nature of these solutions, we parallelized our computations to run on BYU's supercomputer.
            </p>


            <h3>Work</h3>

            <p>
              My graduate work routinely required solutions of boundary value problems (BVPs), and led me to look at Python solvers.
              Two projects have grown out of that. One is a pseudospectral BVP solver implemented in Python.
              The other is porting to Python a 6th order collocation method implemented in MATLAB by Nick Hale (bvp6c).
            </p>
            <p>
              I am currently working for Linguistic Technologies, Inc, where I am rewriting key modules of the WordMAP writing aides software into Python from their legacy implementations in QuickBASIC.
              This core software can help students self-diagnose their writing ability, and has power to predict student outcomes on national exams.
              The software provides linguistic markers which can then be adopted for other natural language processing tasks.
            </p>
            <!-- <div class="" style="width:60%;float:center;margin-left:20%;margin-right:20%;">
              <img id="imgid" class="img_landing" src="{% static '2017-05-29_Ricketts_Glen.jpg' %}">
              <p> <i>Hiking through Ricketts Glen State Park, PA.</i>
              </p>
            </div> -->
          </div>




        </div>
      </div>
    </div>
  </body>
  <script type="text/javascript" src={% static "main.js" %}></script>
</html>

templates/ds_blog/introduction.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<!-- <style media="screen" type="text/css">

.imagediv{
max-width: 50%;
float:left;
margin: 1em;
margin-bottom: 0em;
margin-left:.5em;
padding-right:8px;
padding-left:0px;
padding-bottom:0px;
}
.trialform{
  display:none;
}
</style> -->



<div class="contain-intro" style="width:900px;height:650px;">
  <h2 style="text-align:left;">About Me</h2>
  <div class="img_intro" style="width:250px;float:left;padding-right:1em;margin-top:20px;">
    <img class="img_intro" src="{% static 'profile_pict.jpg' %}">
  </div>

  <div id="intro_txt" >
    <p style="padding-top:.8em;">
  Hi! My name is Joshua Lytle. I am fascinated with science and scientific computing technology - and got to explore each of these while working on my PhD in mathematics (June 2017).  My favorite tool to use as a data scientist is Python - although R has its own strengths. Python really shines as a general-purpose programming language, with its clear syntax and a wonderful, responsive community of users.
    </p>

    <p>
      When I am not programming, looking up a new cool machine learning algorithm, or exploring a dataset, I can be found working on the classical guitar or spending time with my family.
    </p>
  </div>

  <div style="clear:left;"></div>

</div>

{% endblock %}

templates/ds_blog/linearRegression.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
<!-- <style media="screen" type="text/css">

.imagediv{
max-width: 50%;
float:left;
margin: 1em;
margin-bottom: 0em;
margin-left:.5em;
padding-right:8px;
padding-left:0px;
padding-bottom:0px;
}
.trialform{
  display:none;
}
</style> -->
<div  class="blog_post">
  <h2>Linear Regression</h2>
  <p> There is a sense in which interpolation, and producing a "best-fit" curve are similar processes. A few data points are available (sometimes many), a relationship is assumbed between two or more quantities, and a function is produced that generalizes the relationship beyond the given data points. Sometimes the data is known to be somewhat inaccurate (due to say measurement error) or is known to contain noise from some other source. Problems of interpolation occur when data is sparse but fairly accurate. Larger datasets with noise can often be studied by producing a 'best-fit'curve or performing a linear regression.
  </p>
  <p>Consider the data $\{(x_i,y_i)\}_{i=1}^n$ plotted above. We will show how to determine the straight line $y = mx + b$ that best fits the data, using ordinary least squares. For each data point $x_i$ we can determine the corresponding $y$-coordinate on the straight line, $f(x_i) = mx_i + b$.
  </p>

  <pre>
    <code>
      print(x)
      print(y)
      z = (x*y).return_attribute**2
    </code>
  </pre>
</div>


{% endblock %}